### ISSUE TITLE
Documentation / Settings / Status / Metrics

### ISSUE THREAD

**Issue by mmetc** [crowdsecurity/pfSense-pkg-crowdsec#63]
The landing page (Services->CrowdSec) is overcrowded.

We should move the four sections to separate menus:

 - Metrics -> move under Diagnostics/CrowdSec
 - Status -> move under Status/CrowdSec
 - Settings -> leave under Services/CrowdSec, fix the breadcrumbs (now it displays Security/CrowdSec, should be Package/CrowdSec)

 - CrowdSec (the documentation page) -> I left his last because it can be tricky. The link "Help->About this Page" works for the internal services (ex. DHCP Server) but it                                     links to the netgate.com website. Can we make it point to our page? Maybe see how other packages do it. Our "Settings" page should have a link and recommend following this documentation before taking any action.

**Comment by julienloizelet** [comment]
I worked on this issue here: https://github.com/crowdsecurity/pfSense-pkg-crowdsec/pull/68

- [x] Metrics -> move under Diagnostics/CrowdSec
- [x] Status -> move under Status/CrowdSec
- [ ] Settings -> leave under Services/CrowdSec, fix the breadcrumbs (now it displays Security/CrowdSec, should be Package/CrowdSec) : Done **but**  I used Services/CrowdSec and not Package/CrowdSec for the breadcrumb. Did not understand why "Package"
- [ ] Last point : I think I don't understand but what I can say:
    - the "Help->About this Page" is a link to "https://docs.netgate.com/pfsense/help?page=current-page". It is hardcoded in a pfsense file (usr/local/www/help.php) .
  I guess we could do some javascript to modify this link but I don't know where you want to point ( ? ). 
  So, my first question is : where do you want the "documentation" page to be ?


Other remarks: 
- It seems that we can not used the same name for different menu item: Even if item are on separate menu, I was not able to use "CrowdSec" for the 3 menus (Services, Diagnostics, Status) and I had to rename it like "CrowdSec", "CrowdSec status" and "CrowdSec metrics" (just to have a different name)

- As section are now on different part, I removed some tabs in pages : 

![Capture d’écran du 2023-10-13 14-23-21](https://github.com/crowdsecurity/pfSense-pkg-crowdsec/assets/20956510/ee4a9236-4429-424a-8080-95662cf6c337)
![Capture d’écran du 2023-10-13 14-24-16](https://github.com/crowdsecurity/pfSense-pkg-crowdsec/assets/20956510/a2f85ce2-adb3-4fcc-ac11-3cd3f840f7c2)
![Capture d’écran du 2023-10-13 14-24-27](https://github.com/crowdsecurity/pfSense-pkg-crowdsec/assets/20956510/1aab7504-1f06-44e5-adcd-1ae3ea767fba)

**Comment by julienloizelet** [comment]
As we said, I finally did this: 

- the Services -> Crowdsec menu item should point to the settings page
- In the setting page, we will have 2 links (from left to right) : Settings and Documentation

![Capture d’écran du 2023-10-13 16-34-01](https://github.com/crowdsecurity/pfSense-pkg-crowdsec/assets/20956510/440707de-f488-4849-a869-25973823f0c2)
